../../memo_ae/app/mlc_linux/mlc --latency_matrix 
../../memo_ae/app/mlc_linux/mlc --latency_matrix 
../../memo_ae/app/mlc_linux/mlc --latency_matrix 
../../memo_ae/app/mlc_linux/mlc --latency_matrix 
../../memo_ae/app/mlc_linux/mlc --latency_matrix 
../../memo_ae/app/mlc_linux/mlc --latency_matrix 
../../memo_ae/app/mlc_linux/mlc --latency_matrix 
../../memo_ae/app/mlc_linux/mlc --latency_matrix 
../../memo_ae/app/mlc_linux/mlc --latency_matrix 
../../memo_ae/app/mlc_linux/mlc --latency_matrix 
../../memo_ae/app/mlc_linux/mlc --latency_matrix 
../../memo_ae/app/mlc_linux/mlc --latency_matrix 
../../memo_ae/app/mlc_linux/mlc --latency_matrix 
../../memo_ae/app/mlc_linux/mlc --latency_matrix 
../../memo_ae/app/mlc_linux/mlc --latency_matrix 
../../memo_ae/app/mlc_linux/mlc --latency_matrix 
